# Generated by Django 6.0.2 on 2026-03-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scholarship",
            old_name="provider",
            new_name="organization",
        ),
    ]

