# Generated by Django 6.0.2 on 2026-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_rename_provider_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='amount_display',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
