# Generated by Django 6.0.2 on 2026-03-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_scholarship_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
