# Generated by Django 6.0.2 on 2026-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0011_scholarship_category_scholarship_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='category',
            field=models.CharField(blank=True, choices=[('STEM', 'Engineering & Tech'), ('Business', 'Business'), ('Arts & Humanities', 'Arts & Humanities'), ('Medicine & Health', 'Medicine & Health'), ('Social Sciences', 'Social Sciences'), ('Law', 'Law'), ('Education', 'Education'), ('Other', 'Other')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='level',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Degree'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Postdoc', 'Postdoc'), ('Other', 'Other')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_level',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Degree'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Postdoc', 'Postdoc'), ('Other', 'Other')], default='', max_length=30),
        ),
    ]
