services:
  - type: web
    name: scholarship-dashboard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: scholarship-dashboard-db
          property: connectionString
      - key: SERVE_MEDIA_FILES
        value: "true"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.smtp.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp-relay.brevo.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "true"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: SUPPORT_EMAIL
        sync: false

databases:
  - name: scholarship-dashboard-db
    plan: free
