# Generated by Django 6.0.2 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0005_application_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="full_name",
            new_name="student_name",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="motivation",
            new_name="motivation_letter",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="attachment",
            new_name="cv",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="created_at",
            new_name="date_applied",
        ),
        migrations.AlterField(
            model_name="application",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cv/"),
        ),
        migrations.AddField(
            model_name="application",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/"),
        ),
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-date_applied"]},
        ),
    ]

