# Generated by Django 6.0.2 on 2026-03-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_application_files_and_renames'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scholarship_images/'),
        ),
    ]
