# Generated by Django 6.0.2 on 2026-03-17 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0010_contactmessage_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='category',
            field=models.CharField(blank=True, choices=[('STEM', 'STEM'), ('Business', 'Business'), ('Arts & Humanities', 'Arts & Humanities'), ('Medicine & Health', 'Medicine & Health'), ('Social Sciences', 'Social Sciences'), ('Law', 'Law'), ('Education', 'Education'), ('Other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='level',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Postdoc', 'Postdoc'), ('Other', 'Other')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Academic', 'Academic document'), ('Other', 'Other')], default='Academic', max_length=30)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='application_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scholarships.application')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_country', models.CharField(blank=True, max_length=100)),
                ('preferred_level', models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Postdoc', 'Postdoc'), ('Other', 'Other')], default='', max_length=30)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('qualifications', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='profile_cvs/')),
                ('notify_new_scholarships', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
